version: '3.9'
name: 'thefastway'
services:
  postgres:
    container_name: thefastwaydb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ${HOME}/docker/postgresData:/var/lib/postgresql/data
# docker-compose -f .docker/docker-compose.yml --env-file .env up -d
